# Theme Settings
#remote_theme           : "mmistakes/minimal-mistakes"
remote_theme: "mmistakes/minimal-mistakes@4.27.1"
minimal_mistakes_skin    : "contrast" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "en-US"
title                    : "AutoAlgoLLM"
title_separator          : "|"
subtitle                 : "Automated Algorithm Design with Large Language Models"
name                     : "AutoAlgoLLM"
description              : "Research project on automated algorithm design using large language models."
url                      : "https://FeiLiu36.github.io" # Replace with your GitHub username
baseurl                  : "/automated_algorithm_design_llm" # Replace with your repository name
repository               : "FeiLiu36/automated_algorithm_design_llm" # Replace with your GitHub username/repo-name
teaser                   : "/assets/images/teaser.jpg" # Create a teaser image for your project
logo                     : "/assets/images/logo.png" # Create a logo for your project
masthead_title           : "AutoAlgoLLM"
breadcrumbs              : true
words_per_minute         : 200
enable_copy_code_button  : true
search                   : true
search_full_content      : true
search_provider          : lunr
lunr:
  search_within_pages    : true

# Banner Settings
header:
  overlay_image          : "/assets/images/banner.jpg"  # Add a banner image
  overlay_filter         : 0.5  # Darken the banner image (0 to 1.0)
  actions:
    - label: "Learn More"
      url: "/papers/"

# SEO Related
google_site_verification : # Add if needed
og_image                 : "/assets/images/site-logo.png" # Create a site logo for social sharing

# Analytics
analytics:
  provider               : "google-gtag" # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          : # Add your Google Analytics tracking ID if needed
    anonymize_ip         : false

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/FeiLiu36/automated_algorithm_design_llm" # Replace with your GitHub repository
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: # Add if applicable

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - minimal-mistakes-jekyll.gemspec
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Outputting
permalink: /:categories/:title/
timezone: America/New_York # Change to your timezone

# Pagination
paginate: 5
paginate_path: /page:num/

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Defaults
defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false  # Removed team info from sidebar
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false  # Removed team info from sidebar
      read_time: true
      comments: false
      share: true
      related: true
  # paper_list
  - scope:
      path: "_pages/paper-list"
      type: pages
    values:
      layout: single
      author_profile: false
      sidebar:
        nav: "papers"
  # resources
  - scope:
      path: "_pages/resources"
      type: pages
    values:
      layout: single
      author_profile: false
      sidebar:
        nav: "resources"
  # platform
  - scope:
      path: "_pages/platform"
      type: pages
    values:
      layout: single
      author_profile: false
      sidebar:
        nav: "platform"
  # contact
  - scope:
      path: "_pages/contact"
      type: pages
    values:
      layout: single
      author_profile: false  # Removed team info from sidebar
  # term
  - scope:
      path: "_pages/term"
      type: pages
    values:
      layout: single
      author_profile: false
